sudo: required
#language: android
#jdk: oraclejdk8
language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-28.0.0

    # The SDK version used to compile your project
    - android-28

#script:
#- chmod +x ./gradlew

before_script:
 - chmod +x gradlew
script:
- ./gradlew build --stacktrace